spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
      org:
        hibernate:
          envers:
            audit_table_suffix: _history
            store_data_at_delete: true
    open-in-view: false
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test
